Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -50,13 +50,33 @@ jobs:
           rm -rf "$repo_name"
         done
 
+          
     - name: Apply Branch Protection Rules
-      env:
-        RULESET_TOKEN: ${{ secrets.RULESET_TOKEN }}
       run: |
         IFS=' ' read -r -a urls <<< "$repository_urls"
         for repo_url in "${urls[@]}"; do
           repo_name=$(basename "$repo_url" .git)
-          curl -X PUT -H "Authorization: token ${{ secrets.RULESET_TOKEN }}" \
+          echo "Applying protection rules to: ${repo_name}"
+          curl -X PUT -H "Authorization: token ${{ secrets.RULESET_GIT }}" \
           -H "Accept: application/vnd.github.v3+json" \
-          "https://api.github.com/repos/${repo_name}/
+          -d '{
+            "required_status_checks": {
+              "strict": true,
+              "contexts": []
+            },
+            "enforce_admins": true,
+            "required_pull_request_reviews": {
+              "dismiss_stale_reviews": true,
+              "require_code_owner_reviews": true,
+              "required_approving_review_count": 2
+            },
+            "restrictions": {
+              "users": ["devops-user", "devops-bot"],
+              "teams": ["devops-team"]
+            },
+            "required_linear_history": true,
+            "allow_force_pushes": false,
+            "allow_deletions": false
+          }' \
+          "https://api.github.com/repos/${repo_name}/branches/${{ github.event.inputs.branch_name }}/protection" || { echo "Failed to apply protection rules for ${repo_name}"; exit 1; }
+
